#!/bin/sh -xe
trap broadcast_failure 0
usage(){
2>&1 cat <<EOF
TYPICAL USAGE

  MM_URL=url $0 watch-file

DESCRIPTION

  Writes the branches that will expire in number-of-days to the
  channel specified by the URL incoming hook.

  Each line of the watch-file must be in the format

    snap ndays ids-to-ping

  To generate use

    surl -e {your@snapstore.email} -p package_release -p package_access \
         -s production --snap {snap} -a {snap}

ENVIRONMENT

    MM_URL: The incoming hook to the Mattermost channel.

    APILOG: API responses are be appended to that file.

    DRYRUN: If equal to true, prints the results that would be sent to
            Mattermost to stdout, nullifying effect of MM_URL.

EXIT VALUES

   4 if no branch is to expire in number-of-days;
   0 if one branch is to expire in number-of-days;
  20 if dependency is missing;
  21 if this error message is displayed;
   ? if unexpected error occurs.
EOF
    exit 21
}
require(){
    for cmd in "$@"; do
        if ! command -v "$cmd" >/dev/null; then
            2>&1 echo "$cmd missing"
            exit 20
        fi
    done
}
#Take stdin, remove double quotes and dispatch it in the correct format to
#a Mattermost hook.
broadcast(){
    if test "$DRYRUN" = true; then
        return
    fi
    s=$(sed 's/"//g')
    info='Snap branch expiration warning [bot](https://github.com/canonical/snap-expire).
          The following branches will expire in the next days. Close them or bump them with `snap release <CHANNEL> <REVISION>`.
          If you do nothing, the bot will itself *attempt* to bump the channels one day before their expiration.'
    s=$(printf '{"text":"%s\n```\n%s\n```\n%s"}' "$info" "$s" "$pingList")
    curl -s -X POST -H 'Content-Type:application/json' -d "$s" "$1"
}

broadcast_failure(){
    #The trap will always be run on exit, so actually check if some error was
    #returned before proceeding with the failure broadcast.
    test "$?" = 0 && exit
    pingList="@nteodosio"
    echo "The bot is in an unreliable state. Logs: $ACTION_URL" | broadcast "$MM_URL"
}

broadcast_debug(){
    s=$(sed 's/"/\\"/g')
    s=$(printf '{"text":"```\n%s\n```"}' "$s")
    curl -s -X POST -H 'Content-Type:application/json' -d "$s" "$1"
}
#Expects parsed input such as
# "llvm-chromium\t2026-03-26T00:00:00Z\tamd64\tlatest/stable/core22\t67"
# "llvm-chromium\t2026-03-26T00:00:00Z\tarm64\tlatest/stable/core22\t66"
# "llvm-chromium\t2026-03-26T00:00:00Z\tarmhf\tlatest/stable/core22\t65"
#Where $1 is the snap, $2 its expiration, $(NF-1) as channel, $NF as revision
rerelease_snaps_expiring_tomorrow(){
    url="https://dashboard.snapcraft.io/dev/api/snap-release/"
    awk -v today="$(date -u +%FT%TZ)" -v url="$url" -f snap-releaser.awk
}

require surl jq curl datediff awk

if [ $# != 1 ]; then
    usage
fi

unparsed=$(mktemp)
toExpire=$(mktemp)
while read -r snapname ndays ping; do
    case "$snapname" in "#"*) continue;; esac
    apiurl="https://dashboard.snapcraft.io/api/v2/snaps/$snapname/channel-map"
    surl -a "$snapname" -s production "$apiurl" > "$unparsed"
    [ -n "$APILOG" ] && cat "$unparsed" >> "$APILOG"
    if <"$unparsed" grep -q macaroon-authorization-required; then
        >>"$toExpire" echo "$ping: Authorization secret for $snapname expired!"
        pingList="$pingList $ping"
        hasResult=1
    fi
    if <"$unparsed" >>"$toExpire" jq -e \
      --arg til "$(date --date="today + $ndays days" +%s)" \
      --arg snapname "$snapname" -f channel-map-api-parser; then
        pingList="$pingList $ping"
        hasResult=1
        hasSnapToExpire=1
    fi
done <"$1"

if test -n "$hasSnapToExpire"; then
    <"$toExpire" rerelease_snaps_expiring_tomorrow
fi

# In a public repository, scheduled workflows are automatically disabled
# by Github when no repository activity has occurred in 60 days.
lastCommitDaysAgo=$(datediff "$(git log -1 --format=%cs)" "$(date +%F)")
if [ "$lastCommitDaysAgo" -ge 55 ]; then
    hasResult=1
    pingList="$pingList @nteodosio"
    echo "This bot will soon die because last commit was $lastCommitDaysAgo d" \
    "ago and Github disables workflows in 60 days of inactivity." >>"$toExpire"
fi

echo "The snaps that would be broadcasted to expire are in $toExpire."
if test -n "$hasResult"; then
    if test "$DRYRUN" = true; then
        cat "$toExpire"
    elif test -n "$MM_URL"; then
        <"$toExpire" broadcast "$MM_URL"
    fi
fi
if test -n "$API_DUMP_MM_URL"; then
    <"$APILOG" broadcast_debug "$API_DUMP_MM_URL"
fi
