name: Checks
on: [push, pull_request]
jobs:
  sh-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt install -y shellcheck
          shellcheck -S warning snap-expire
